import React, { useState, useEffect, useRef } from 'react';
import { Heart, Sparkles, ChevronUp, ChevronDown, Bookmark, Link, BookmarkCheck, ArrowLeft, X, Search, Banknote, Star, User, Plus } from 'lucide-react';
import { DollarBillIcon } from './components/DollarBillIcon';
import { HealthIcon } from './components/HealthIcon';

const loveAffirmations = [
  "I am worthy of deep love",
  "Love flows to me effortlessly", 
  "I attract love with ease",
  "My heart is open to love",
  "I radiate love and receive love",
  "Love surrounds me always",
  "I deserve unconditional love",
  "Love is my natural state",
  "I am a magnet for love",
  "Love fills every cell of my being",
  "I give and receive love freely",
  "My heart overflows with love",
  "Love is always available to me",
  "I am love in human form",
  "Love guides all my actions",
  "I trust in love's perfect timing",
  "Love heals and transforms me",
  "I am surrounded by loving energy",
  "Love is my greatest strength",
  "I choose love in every moment",
  "Love connects me to all beings",
  "I am deeply loved and cherished",
  "My capacity for love is infinite",
  "I attract my perfect soulmate",
  "Love multiplies when I share it",
  "I am worthy of passionate love",
  "My heart chakra is wide open",
  "I forgive myself with love",
  "Love is the answer to everything",
  "I am a beacon of pure love",
  "My relationships are filled with love",
  "I speak words of love and kindness",
  "Love flows through me to others",
  "I am grateful for all the love in my life",
  "My soul recognizes its perfect match",
  "I trust the universe to bring me love",
  "Love is my default emotion",
  "I am loveable exactly as I am",
  "My heart is a fountain of love",
  "I attract love in all its forms",
  "Love is my superpower",
  "I am surrounded by loving souls",
  "My love story is beautiful and unique",
  "I deserve a love that celebrates me",
  "Love comes to me at the perfect time",
  "I am open to receiving deep love",
  "My heart beats with pure love",
  "I create loving relationships effortlessly",
  "Love is my birthright",
  "I am worthy of epic love",
  "My love attracts my ideal partner",
  "I radiate love wherever I go",
  "Love finds me wherever I am",
  "I am a master of self-love",
  "My heart is healed and whole",
  "Love transforms everything it touches",
  "I am divinely guided to love",
  "My love is a gift to the world",
  "I choose love over fear always",
  "Love is my natural frequency",
  "I am worthy of unconditional acceptance",
  "My heart is a magnet for true love",
  "Love flows to me like a river",
  "I am love walking in human form",
  "My soul mate is seeking me too",
  "Love is my greatest adventure",
  "I trust in love's divine timing",
  "My heart is open to miracles",
  "Love is the essence of who I am",
  "I am worthy of a fairy tale love",
  "My love creates positive change",
  "I attract love that honors my worth"
];

const wealthAffirmations = [
  "I am a money magnet",
  "Wealth flows to me easily",
  "I attract abundance effortlessly",
  "Money comes to me from multiple sources",
  "I am worthy of financial success",
  "Prosperity is my natural state",
  "I create wealth through value",
  "My income increases daily",
  "I am financially free",
  "Money works for me",
  "I attract lucrative opportunities",
  "Wealth is drawn to me",
  "I am a successful entrepreneur",
  "My business thrives and grows",
  "I make smart financial decisions",
  "Abundance surrounds me always",
  "I deserve unlimited prosperity",
  "Money flows like water to me",
  "I am rich in all areas",
  "Financial success is inevitable",
  "I attract profitable ventures",
  "My wealth multiplies exponentially",
  "I am open to receiving money",
  "Success follows me everywhere",
  "I create multiple income streams",
  "My business generates massive profits",
  "I am a wealth creator",
  "Money loves me and I love money",
  "I attract high-paying clients",
  "My net worth increases constantly",
  "I am financially abundant",
  "Prosperity flows through me",
  "I manifest money with ease",
  "My business scales effortlessly",
  "I attract investment opportunities",
  "Wealth is my birthright",
  "I am a money-making machine",
  "Financial freedom is mine",
  "I attract passive income streams",
  "My business empire grows daily",
  "I am worthy of massive wealth",
  "Money comes to me in unexpected ways",
  "I create value and receive abundance",
  "My financial goals manifest quickly",
  "I am a master of money",
  "Wealth creation is my superpower",
  "I attract millionaire opportunities",
  "My business dominates the market",
  "I am financially unstoppable",
  "Money flows to me like a river",
  "I am a magnet for financial miracles",
  "Wealth consciousness is my default state",
  "I attract money while I sleep",
  "My bank account grows exponentially",
  "I am worthy of unlimited abundance",
  "Money comes to me from everywhere",
  "I create wealth with my thoughts",
  "My business is a cash cow",
  "I attract wealthy mentors and partners",
  "Financial abundance is my reality",
  "I am a master wealth builder",
  "Money flows to me effortlessly",
  "I deserve to be financially free",
  "My income exceeds my expenses",
  "I attract profitable investments",
  "Wealth is attracted to my energy",
  "I am financially independent",
  "Money multiplies in my hands",
  "I create value that generates wealth",
  "My business attracts ideal customers",
  "I am a successful money manager",
  "Abundance is my natural state",
  "I attract money-making opportunities",
  "My wealth serves the highest good",
  "I am worthy of financial security",
  "Money comes to me in perfect timing",
  "I create multiple revenue streams",
  "My business generates passive income",
  "I attract financial windfalls",
  "Wealth flows to me consistently",
  "I am a money manifestation master",
  "My financial future is bright",
  "I attract abundance in all forms",
  "Money is my faithful servant",
  "I create wealth through innovation",
  "My business scales automatically",
  "I attract high-value opportunities",
  "Financial success is my destiny",
  "I am worthy of extreme wealth",
  "Money loves to work for me",
  "I attract profitable partnerships",
  "My wealth creates positive impact",
  "I am financially bulletproof",
  "Money flows to me like magic",
  "I create wealth through service",
  "My business is incredibly profitable"